import type { Metadata } from "next";
import "@/styles/globals.css";
import { Noto_Sans } from "next/font/google";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-noto-sans", // カスタムプロパティ名
});

export const metadata: Metadata = {
  title: "ReLearn",
  description: "Generated by create next app",
  icons: "/logo/favicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={notoSans.variable}>{children}</body>
    </html>
  );
}
