name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest # 使用するOSの指定（Ubuntuを使用）

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # コードをリポジトリから取得

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Node.jsのセットアップ
        with:
          node-version: "20" # 使用するNode.jsのバージョン
      
      - name: Set up .env
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
    

      - name: Install dependencies
        run: yarn install # 依存関係のインストール
      
      # - name: Run Prisma migrations
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #   run: |
      #     yarn prisma migrate deploy
      #     yarn prisma generate

      - name: Run Prettier
        run: yarn prettier --check .

      - name: Run ESLint
        run: yarn lint # ESLintによるコードチェック

      - name: Run tests
        run: yarn test --passWithNoTests # テスト実行

      - name: Build project
        run: yarn build # プロジェクトのビルド
      
