name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest # 使用するOSの指定（Ubuntuを使用）

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # コードをリポジトリから取得

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Node.jsのセットアップ
        with:
          node-version: "20" # 使用するNode.jsのバージョン

      - name: Set up .env
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

      - name: Install dependencies
        run: yarn install # 依存関係のインストール

      # localhost:3000サーバーを起動
      - name: Start Next.js server
        run: yarn dev &
        env:
          PORT: 3000

      # サーバー起動まで待機
      - name: Wait for localhost:3000
        run: |
          echo "Waiting for server to start..."
          for i in {1..30}; do
            curl -sSf http://localhost:3000 > /dev/null && echo "Server is up!" && break
            echo "Server is not ready yet. Retrying in 2 seconds..."
            sleep 2
          done

      - name: Run Prettier
        run: yarn prettier --check .

      - name: Run ESLint
        run: yarn lint # ESLintによるコードチェック

      - name: Run tests
        run: yarn test --passWithNoTests # テスト実行

      - name: Build project
        run: yarn build # プロジェクトのビルド
